# Generated by Django 5.0.1 on 2024-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilermate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=200)),
                ('topics', models.TextField()),
                ('videoUrls', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
