# Generated by Django 5.0.1 on 2024-02-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilermate_app', '0002_classes_delete_user_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='videoUrls',
        ),
    ]
