# Generated by Django 5.0.1 on 2024-02-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilermate_app', '0003_remove_classes_videourls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='classes',
            new_name='name',
        ),
    ]
