# Generated by Django 5.0.1 on 2024-02-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilermate_app', '0004_rename_classes_classes_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='topics',
            new_name='links',
        ),
    ]
